name: aptbrowser
version: 0.2
summary: Browse your apt dependencies
description: Browse your apt cache dependencies
confinement: strict 
grade: devel 

apps:
  run: 
    command: desktop-launch aptbrowser 
    plugs: [unity7, opengl, network-bind, gsettings, browser-support, pulseaudio]

parts:
    application:
        plugin: cmake
        source: . 
        build-packages:
          - build-essential
          - cmake
          - gettext
          - intltool
          - pkg-config
        after: [desktop-qt5]

    qt:
        plugin: nil
        stage-packages:
          - liboxideqt-qmlplugin
          - qtubuntu-desktop
          - qtdeclarative5-ubuntu-content1
          - ubuntu-sdk-libs
          - libsdl2-2.0-0
          - libqt5quick5
          - qml-module-qtquick2
          - qml-module-qtquick-window2
          - qml-module-qtquick-layouts
          - qml-module-qtquick-controls
          - locales-all

    environment:
        plugin: dump
        source: .
        organize:
            aptbrowser.wrapper: bin/aptbrowser
            snappy-qt5.conf: etc/xdg/qtchooser/snappy-qt5.conf
