name: aptbrowser
version: 0.2.3
summary: Browse your apt dependencies
description: Browse your apt cache dependencies
confinement: strict 
grade: devel 

apps:
  run: 
    command: desktop-launch aptbrowser
    plugs: [platform, unity7, opengl, network-bind, gsettings, browser-support, pulseaudio]

plugs:
    platform:
        interface: content
        content: ubuntu-app-platform1
        default-provider: ubuntu-app-platform
        target: ubuntu-app-platform

parts:
    application:
        after: [desktop-ubuntu-app-platform]
        plugin: cmake
        source: . 
        build-packages:
          - build-essential
          - cmake
          - gettext
          - intltool
          - pkg-config
    environment:
        plugin: dump
        source: .
        organize:
            aptbrowser.wrapper: bin/aptbrowser
