name: aptbrowser
version: 0.1
summary: Browse your apt dependencies
description: Browse your apt cache dependencies
confinement: devmode

apps:
  aptbrowser: 
    command: desktop-launch aptbrowser 
    plugs: [unity7, opengl, network-bind]

parts:
    application:
        plugin: cmake
        source: . 
        build-packages:
          - build-essential
          - cmake
          - gettext
          - intltool
          - libapparmor-dev
          - pkg-config
        stage-packages:
          - fonts-liberation
          - liboxideqt-qmlplugin
          - qtubuntu-desktop
          - qtdeclarative5-ubuntu-content1
          - ubuntu-sdk-libs
        snap:
          - -usr/share/doc
          - -usr/include
        after: [desktop/qt5]

    environment:
        plugin: copy
        files:
            aptbrowser.wrapper: bin/aptbrowser
